# Uncomment this line to define a global platform for your project
platform :ios, "6.0"
inhibit_all_warnings!

target "iParticipate" do
pod 'CKSideBarController', :podspec => 'https://raw.github.com/MaxKramer/CKSideBarController/master/CKSideBarController.podspec'
pod 'SVProgressHUD'
end

target "iParticipateTests" do

end

